/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GmUserDetail {
    /**
    * The nickname
    */
    'nickname': string;
  }
}

declare global {


  interface HTMLGmUserDetailElement extends Components.GmUserDetail, HTMLStencilElement {}
  var HTMLGmUserDetailElement: {
    prototype: HTMLGmUserDetailElement;
    new (): HTMLGmUserDetailElement;
  };
  interface HTMLElementTagNameMap {
    'gm-user-detail': HTMLGmUserDetailElement;
  }
}

declare namespace LocalJSX {
  interface GmUserDetail extends JSXBase.HTMLAttributes<HTMLGmUserDetailElement> {
    /**
    * The nickname
    */
    'nickname'?: string;
  }

  interface IntrinsicElements {
    'gm-user-detail': GmUserDetail;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


